apiVersion: v1
kind: Service
metadata:
  name: nx-poc-service
  labels:
    app: nexusapp-ecr
spec:
  selector:
    app: nexusapp-ecr

  ports:
    - port: 80
      targetPort: 5173

  type: LoadBalancer
